UAF-364 Added environment mapping to app versions

diff --git a/bin/tomcat-ctl b/bin/tomcat-ctl
--- a/bin/tomcat-ctl
+++ b/bin/tomcat-ctl
@@ -37,6 +37,31 @@ tomcat_start () {
             mkdir $TOMCAT_KFS_DIR
         fi
         
+        # Figure out what artifact we need for this application environment
+        case "$KFS_ENV_NAME" in
+            'dev')
+                   APP_VERSION=$KFS_VERSION_DEV
+                   APP_REPO=$KFS_REPOSITORY_DEV
+                   ;;
+            'tst')
+                   APP_VERSION=$KFS_VERSION_TST
+                   APP_REPO=$KFS_REPOSITORY_TST
+                   ;;
+            'stg')
+                   APP_VERSION=$KFS_VERSION_STG
+                   APP_REPO=$KFS_REPOSITORY_STG
+                   ;;
+            'prd')
+                   APP_VERSION=$KFS_VERSION_PRD
+                   APP_REPO=$KFS_REPOSITORY_PRD
+                   ;;
+            *)
+                echo "Invalid KFS_ENV_NAME: $KFS_ENV_NAME." >> $LOGS_DIRECTORY/kfs-startup.log
+                echo "Invalid KFS_ENV_NAME: $KFS_ENV_NAME."
+                exit 1
+                   ;;
+        esac
+        
         # Download the WAR file if it doesn't exist
         WAR_FILE="$TOMCAT_KFS_DIR/kfs.war"
         echo "Looking for $WAR_FILE..."
@@ -44,7 +69,7 @@ tomcat_start () {
         then
             MAVEN_SERVER="https://ka-tools.mosaic.arizona.edu/nexus"
             MAVEN_ENDPOINT="$MAVEN_SERVER/service/local/artifact/maven/redirect"
-            WAR_SOURCE_URL="$MAVEN_ENDPOINT?r=snapshots&g=org.kuali.kfs&a=kfs-web&v=ua-release1-SNAPSHOT&c=ua-ksd&p=war"
+            WAR_SOURCE_URL="$MAVEN_ENDPOINT?r=$APP_REPO&g=org.kuali.kfs&a=kfs-web&v=$APP_VERSION&c=ua-ksd&p=war"
             curl -L "$WAR_SOURCE_URL" -o $WAR_FILE           
             chown kualiadm:kuali $WAR_FILE
             # Extract the WAR file
@@ -52,6 +77,7 @@ tomcat_start () {
             jar -xf $WAR_FILE
         fi
 
+        echo "Downloaded $WAR_SOURCE_URL" >> $LOGS_DIRECTORY/kfs-startup.log
         echo "Starting Tomcat application server tomcat ..." >> $LOGS_DIRECTORY/kfs-startup.log
 
         # copy in tomcat configuration files
